# Rebuilds Icons.cs from the *-light.svg / *-dark.svg files next to it. Run from the Icons folder.
$dir = $args[0]; if (-not $dir) { $dir = $PWD.Path }
$utf8 = New-Object System.Text.UTF8Encoding($false)
$uri = { param($f) 'data:image/svg+xml;base64,' + [Convert]::ToBase64String($utf8.GetBytes(([IO.File]::ReadAllText($f, $utf8)).TrimEnd())) }
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine(@'
// <auto-generated> Regenerate with Icons\README.md "Regenerating" (the SVGs in this folder are the source).
// Icons for the MCP server identity, tools, apps/resources and prompts (MCP 2026-07-28 icons).
using ModelContextProtocol.Protocol;

namespace ExileApiMcp.Hosting;

/// <summary>
/// The server's icon set as data URIs. Each icon comes in a light variant (for light host backgrounds) and a
/// dark variant; <see cref="Pair"/> turns the two into the <see cref="Icon"/> list a tool, resource, prompt or
/// <see cref="Implementation"/> takes. The values are consts so they can also go into attribute arguments
/// such as <c>[McpServerTool(IconSource = IconSet.PlayerStatsLight)]</c>.
/// </summary>
public static class IconSet
{
    public const string MimeType = "image/svg+xml";

    /// <summary>Two icons for the same meaning: the light-background and the dark-background variant.</summary>
    public static IList<Icon> Pair(string light, string dark) =>
    [
        new Icon { Source = light, MimeType = MimeType, Sizes = ["any"], Theme = "light" },
        new Icon { Source = dark, MimeType = MimeType, Sizes = ["any"], Theme = "dark" },
    ];
'@)
$order = 'Server', 'PlayerStats', 'DataExplorer', 'MemoryView', 'HudPerformance', 'Timeline', 'Guide', 'Knowledge'
$names = Get-ChildItem $dir -Filter '*-light.svg' | ForEach-Object { $_.BaseName -replace '-light$' } | Sort-Object { $i = [array]::IndexOf($order, $_); if ($i -lt 0) { 99 } else { $i } }, { $_ }
foreach ($n in $names) {
  [void]$sb.AppendLine()
  [void]$sb.AppendLine("    public const string ${n}Light = `"$(& $uri (Join-Path $dir "$n-light.svg"))`";")
  [void]$sb.AppendLine("    public const string ${n}Dark = `"$(& $uri (Join-Path $dir "$n-dark.svg"))`";")
  [void]$sb.AppendLine("    public static IList<Icon> $n => Pair(${n}Light, ${n}Dark);")
}
[void]$sb.AppendLine('}')
[IO.File]::WriteAllText((Join-Path $dir 'Icons.cs'), $sb.ToString(), $utf8)
"wrote $(Join-Path $dir 'Icons.cs') ($($names.Count) icons)"
