// Stable data-tour ids: the pages mark these elements, the tours target them. Add here, never inline strings.
export const T = {
  nav: "nav",
  navOverview: "nav-overview",
  navTools: "nav-tools",
  navSettings: "nav-settings",
  navObserver: "nav-observer",
  navPerf: "nav-perf",
  huds: "huds",
  livePill: "live-pill",
  showMe: "show-me",
  // overview
  healthCard: "health-card",
  healthWatch: "health-watch",
  observerCard: "observer-card",
  quickActions: "quick-actions",
  // tools
  toolSearch: "tool-search",
  toolFamilies: "tool-families",
  toolList: "tool-list",
  toolBadges: "tool-badges",
  toolForm: "tool-form",
  toolCall: "tool-call",
  toolResult: "tool-result",
  toolResultTabs: "tool-result-tabs",
  toolHistory: "tool-history",
  // settings
  settingsPull: "settings-pull",
  settingsSearch: "settings-search",
  settingsPlugin: "settings-plugin",
  settingsControl: "settings-control",
  settingsPermission: "settings-permission",
  settingsUndo: "settings-undo",
  // observer
  observeSwitch: "observe-switch",
  layersList: "layers-list",
  layerAdd: "layer-add",
  layerAddPath: "layer-add-path",
  layerAddMode: "layer-add-mode",
  layerAddSubmit: "layer-add-submit",
  layerPreflight: "layer-preflight",
  layerMap: "layer-map",
  layerMapOpen: "layer-map-open",
  eventsFeed: "events-feed",
  eventsFilter: "events-filter",
  // perf page (the embedded app marks nothing; the page wraps it)
  perfPage: "perf-page",
} as const;
